### ISSUE TITLE
Deploy GWELLS change to Prod

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1826]
**Describe the task**
We want a ticket to encapsulate the effort required for our first deployment to production for this repository.

**Acceptance Criteria**
- [ ] GWELLS#1818
- [ ] We have an understanding of how to deploy code to GWELLS

**Additional context**
- We will have one of these tickets for each repository

**Comment by norrisng-bc** [comment]
The pipeline is up and running (and so is the corresponding documentation), but builds are failing.

The following errors are of particular interest:
```
error in GDAL setup command: use_2to3 is invalid.
```
```
ERROR: Could not find a version that satisfies the requirement GDAL<3.0,>=2.4 (from versions: 1.5.0, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.11.2, 2.0.0, 2.0.1, 2.1.0, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.2, 2.4.3, 2.4.4, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0, 3.2.1, 3.2.2, 3.2.2.1, 3.2.3, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0, 3.5.0.3, 3.5.1)
ERROR: No matching distribution found for GDAL<3.0,>=2.4
```

It appears that [GDAL doesn't support `setuptools` 58.0.0 and later](https://github.com/pypa/setuptools/issues/2781#issuecomment-917185367).

Now, this would be fine since the base image for the backend (see `gwells/openshift/docker/backend/Dockerfile`) [comes with `setuptools` 36.6.0](https://catalog.redhat.com/software/containers/rhscl/python-36-rhel7/599328ef5a13466ac6ac36aa?container-tabs=packages).

For some reason, however, `pip` gets upgraded, which also upgrades `setuptools` to 59.6.0, breaking the GDAL install process.

The solution would be to somehow override/disable updating `setuptools`, such that it installs 57.5.0 (the last version before 58) instead.
