### ISSUE TITLE
Provide Access to GWELLS DB for Service Owner

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#1845]
**As a** *Service Owner* **I want** *to be able to query the DB* **So That** *I can pull data for reports*

**Additional Context**
- we are giving Service Owner access to the DB as she knows how to write SQL queries
- this is a short term solution with the long term solution being to implement something like metabase so more people have access to the data
- Julian to add details of what needs to change

**Acceptance Criteria**
- [x] Service Owner can query DB
- [x] Service owner knows what they are not allowed to do in the DB

**Comment by JulianForeman** [comment]
We might run into an issue where files don't carry over between deployments since this was done directly in a pod console not in the bc/dc.  So if that happens we will need to figure out how to edit the hba_file config to adjust the rules allowing outside users to port-forward into the database.  As well as adding a read only user (to prevent mistakes) for the current SO.
