### ISSUE TITLE
Research Upgrading Keycloak to Gold Common Realm for GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1863]
**Describe the task**
To research and understand how to switch the Keycloak realm the application is using

**Acceptance Criteria**
- [ ] We understand Keycloak as a tool
- [ ] We understand how Keycloak is being used by this application
- [ ] The functionality can be replicated with Client level roles
- [ ] We understand the work involved from our end to switch the Keycloak realm an app is using and document instructions on how to do it

**Outcome**
To be able to estimate Keycloak tickets

**Additional context**
- In moving from Silver Custom to Common Gold realms (Gov direction as there's a cost to custom realms), can we configure Keycloak/GWELLS to work with client-level roles rather than realm-level roles?

- Link to Keycloak resource(s):
**THE LINKS BELOW WERE COPIED FROM #969. TO BE UPDATED SO THEY ARE RELEVANT TO GWELLS**
https://developer.okta.com/blog/2017/07/25/oidc-primer-part-1
https://github.com/bcgov/sso-keycloak/wiki/zorin-notes-to-run-examples-from-our-team
https://oidc.gov.bc.ca/auth/realms/3l5nw6dk/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https%3A%2F%2Foidc.gov.bc.ca%2Fauth%2Fadmin%2F3l5nw6dk%2Fconsole%2F%23%2Frealms%2F3l5nw6dk%2Fusers&state=b35d72b3-d487-41e6-b8f4-030c87810952&response_mode=fragment&response_type=code&scope=openid&nonce=28d12c81-4f7e-49e7-8f22-a30dfba98b30&code_challenge=hkrkKMG3xjEgl5xGKZyZoZ3nzKAZ-o9PimvHuJSEMY4&code_challenge_method=S256
https://bcgov.github.io/sso-requests
https://github.com/bcgov/sso-keycloak/wiki/test-page

**Comment by norrisng-bc** [comment]
The rough equivalent of a "realm" in Gold is an "integration". Obviously not an actual Keycloak realm since that's now managed by the SSO team, but this would be our own "space" in the shared realm.

GWELLS only makes use of one client (`gwells`), so it should be possible to directly convert realm roles (which we'll no longer have access to) to client roles in Gold.

Rough outline of the migration process:

1. **Request SSO integration on the [Common Hosted SSO self-service app (CSS)](https://bcgov.github.io/sso-requests)**
   * Create a team in CSS first
   * Use "IDIR" and "BCeID both" for identity providers
   * DEV/TEST/PROD Environments will be auto-provisioned within 20 minutes (*exception:* BCeID PROD, see below)
   * BCeID PROD requires approval from the IDIM team - email them at IDIM.Consulting@gov.bc.ca and provide the app name, approval will be quick since GWELLS already has approval for the existing Silver realm
2. **Copy over all realm roles to the Gold realm as client roles**
   * [CSS has an API available](https://github.com/bcgov/sso-keycloak/wiki/CSS-API-Account), could probably write a one-off script to do this, instead of doing so manually via the CSS dashboard
   * [Differences between client/realm roles](https://github.com/bcgov/sso-keycloak/blob/dev/docs/migration-guide.md)
3. **Update frontend and backend code so that it points at the Gold realm, and at client roles instead of realm roles**
   * The SSO self-service dashboard has an "installation JSON" that you can download, which the Keycloak adapter can directly use when placed at the same location as the HTML page being loaded
   * The frontend downloads the adapter ([`keycloak.js`](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter)) from the Keycloak server on login
4. **Fix bugs as they appear (if any)**

The backend database also appears to have several tables that mirror the existing Keycloak realm. It's unclear as to how it's synchronized with what's on Keycloak:

| GWELLS database table      | Keycloak custom realm | Description                                       |
|----------------------------|-----------------------|---------------------------------------------------|
| `auth_group`                 | Groups                | List of permissions groups                        |
| `auth_group_permissions`     | Role mappings         | A grouping of individual permissions              |
| `auth_permission`            | Roles                 | An individual permission                          |
| `auth_user`                  | Users                 | List of authorized/authenticated users            |
| `auth_user_groups`           | Group membership      | Which group(s) is a user in?                      |
| `auth_user_user_permissions` |                       | *Currently empty*                                   |
| `profile`                    |                       | Stores the government-provided GUID for each user.  <br/><br/>Generally, using this GUID to differentiate users is preferred; IDIR usernames can be recycled, and using the Keycloak ID risks vendor lock-in. However, once authenticated, GWELLS uses an internal auto-incrementing integer as the primary key for users.|

*Note:* Keycloak realms are, in turn, mapped to Django groups.

Additional documentation can be found at the [sso-keycloak wiki](https://github.com/bcgov/sso-keycloak/wiki).
