### ISSUE TITLE
Investigate Replacement for BCeID Personal Accounts - GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1929]
**Describe the task**
BCeID Personal accounts are not supported in Keycloak Gold. The solution is to have users switch to BCeID Basic accounts, but we'll need to figure out how to do so without too much of a headache for the users and service owner.

**Purpose**
This will allow us to make the switch to Keycloak Gold.

**Acceptance Criteria**
- [ ] Know what options we have for moving BCeID Personal users to BCeID Basic accounts

**Additional context**
- BCeID Personal account users are verified. If we need that verification feature (we don't, as per service owner), we would have to switch to BC Services Card, which is another identity provider that also requires working with the IDIM team.
- New BCeID Personal accounts have not been offered for 5+ years.
- Are there any other teams that have encountered this same scenario?
- Per Service Owner:
No need for account users to be verified (service owner provisions account access directly)
GWELLS documentation says they can sign up for basic or business account

**Action**
Further discussion with Service Owner needed to determine:
- can we move away from BCeID personal account?
- how many BCeID Personal users are currently active in GWELLS?
- what are the impacts?

**Comment by norrisng-bc** [comment]
As per the service owner, the user verification feature provided by BCeID Personal is not needed - users directly contact the SO who then provisions access. The easiest solution would be to have BCeID Personal users create new BCeID Basic accounts (i.e. not migrate the BCeID Personal accounts) and have them provisioned by the SO.

According to the IDIM team, out of all the BCeID users that GWELLS has a record of, only 6 are Personal accounts and are active; i.e. logged in somewhere (not necessarily GWELLS, could be another service using BCeID login) sometime during the past 27 months. However, due to privacy restrictions, we don't know who those 6 users are.

We could then add a message on the homepage telling users to contact the SO if they cannot login, so that they can have the correct permissions assigned. This could potentially result in user confusion (e.g. users not knowing what type of BCeID account they have), but a short and carefully-crafted message should solve that.

**Comment by norrisng-bc** [comment]
*Update:* above approach confirmed with service owner. 

Homepage message will be implemented as part of #1871.
