### ISSUE TITLE
Quarterly Data Export - GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1959]
**Describe the task**
Export of GWELLS data set to Excel

**Purpose**
GWELLS Service Owner needs a pull of this Data, as the export function doesn't work on queries this large. 

**Acceptance Criteria**
- [ ] GWELLS Service Owner has Export of Data

**Additional context**
- Fields Needed:
WTN
Drilling Company
Well Class Description
Create user name
Create date/time
Construction start date
Alteration date
Decommission date 

Search filter:
Created date: 1 Jan 2023 to 30 April 2023 (inclusive)

**Comment by norrisng-bc** [comment]
Export completed and emailed to service owner.

For posterity, here's the SQL that was run:
```sql
SELECT
	well.well_tag_number,
	registries_organization.name AS drilling_company,
	well_class_code.description AS well_class_description,
	profile.name AS create_user,
	to_char(date_trunc('second', well.create_date AT TIME zone 'America/Vancouver'), 'YYYY-MM-DD HH24:MI:SS') AS create_date,
	well.construction_start_date,
	well.construction_end_date,
	well.alteration_start_date,
	well.alteration_end_date,
	well.decommission_start_date,
	well.decommission_end_date 
FROM
	well 
	LEFT JOIN
		well_class_code 
		ON well.well_class_code = well_class_code.well_class_code 
	LEFT JOIN
		registries_organization 
		ON well.org_of_person_responsible_guid = registries_organization.org_guid 
	LEFT JOIN
		profile 
		ON well.create_user = profile.username 
WHERE
	well.create_date >= '2023-01-01 08:00:00-00' 
	AND well.create_date <= '2023-04-30 07:00:00-00' 
ORDER BY
	well.create_date DESC;

```
(there's probably a much better way of handling timezones when filtering by `well.create_date`)

**For non-technical users:** edit both `well.create_date` values under the `WHERE` block as appropriate. If daylight savings is in effect for a given date, use `07:00:00-00`; otherwise, use `08:00:00-00`.
