### ISSUE TITLE
Make wells records with aquifer parameters searchable and highlighted on the Aquifer Summary page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2052]
**As a** *user* **I want** *wells records with aquifer parameters searchable* **So That** *I can search out aquifers with one or more wells with aquifer parameters correlated to them.

**Additional Context**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXJpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08c3305add452b9686b3920e1f0b74b3bb551460/image.png)
- any aquifer that has 1 or more well with aquifer parameters halo should also appear in search

**Acceptance Criteria**
- [ ] Given I am on the Aquifer Summary page, When I go to the Advance Search, Then I can see the Aquifer parameters is included in the list so that I can check/uncheck
- [ ] Given I am on the Aquifer Summary page, When I check Aquifer parameters and click the search button, Then any aquifer with one or more wells with aquifer parameters correlated to it will be listed.

**Comment by sanjaytkbabu** [comment]
Deployed to staging: https://gwells-staging.apps.silver.devops.gov.bc.ca/gwells

**Comment by sanjaytkbabu** [comment]
New update released to Staging

**Comment by sanjaytkbabu** [comment]
We deployed the fix to https://gwells-staging.apps.silver.devops.gov.bc.ca/gwells to filter out some aquifers without aquifer parameters. 
It might appear that there are still some aquifers showing up without wells having aquifer parameters, We believe this is due to a pre-existing bug with some wells not being displayed in the Aquifer summary hyperlink.
I have created another ticket to address this missing wells issue: https://app.zenhub.com/workspaces/sustainment-team-621fdc6b9ad7010018d8dc2c/issues/gh/bcgov/gwells/2102
Please continue testing and let us know if #2052 is PROD ready.
