### ISSUE TITLE
Data/Rows overwrote by new entries under "Pumping Test Information and Aquifer Parameters"

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2070]
**Describe the Bug**
This bug was originally noticed by uploading an attachment to WTN59354, which results in the removal of rows in the table under "Pumping Test Information and Aquifer Parameters" in "Well Summary" page. Later I tested in staging (WTN28949) and noticed that it can be triggered by any update to the well (any section/field).

- After I add a new pumping test on "Well Editing" page, the "changing history" on "Well Editing" page shows the new entry overwrote/replaced the previous table. This replacement won't be updated on "Well Summary" page (a new entry/row was added to the existing table) until it is triggered by any further editing action of the well.  
**Note:** in some occasions, even the only one that was latest uploaded pumping test data can be gone (empty table) but I can reproduce each time (couldn't figure out the combination of multiple steps, likely include the step of updating the existing test data and the step of updating other fields)

- Also if don't input data for fields of "storativity", "Transmissvity" and "hydrolic Conductivity", it shows "NaN" in the table other than blanks.

**Expected Behaviour**
When adding a well, existing data  won't be lost.

**Actual Behaviour**
The action of well information update results of data lost

** Steps To Reproduce**
Steps to reproduce the behaviour: 
(IN STAGING)
1. Go to WTN 28949 editing page, there is an existing test 
2. Add a new pumping test data by filling at least one field (for example, input 19 in comment) and click save button. 
3. Scroll down to "change history" and click "show" button, the history will indicate this #18 test has been replaced by 19
4. Go to Well Summary page, **error:** "NaN" was displayed in the unfilled fields. At this time, the test 18 is not gone yet.
5. Go back to Editing page, make any changes at any field, then click save. 
6. Go to Well Summary page, **error:** the test 18 is gone and only 19 stays.

**Comment by davidclaveau** [comment]
Added a stopgap fix to prevent further dataloss in this PR: https://github.com/bcgov/gwells/pull/2080

This PR essentially makes it so `aquifer_parameters_set` is never skipped when loading and saving a well, so the data isn't lost on other saves.

The issue requires some more information to properly solve. It might be stemming from the model's serializer and how it saves/retrieves the data through AquiferParameters (`aquifer_parameters_set`) and ensuring the data is maintained during page updates.

Replicating the bug is a little tricky, but can be done like so (after undoing the doNotSkip change in the PR):

1. Add a Pumping Test with fake data. Save.
2. Refresh the page and update the Pumping Test. Save.
3. Refresh the page and go to another section of the well (document upload, lithology, etc.) and update/add data to that field. Save.
-- You should see in the "edit" API call that `aquifer_parameters_set` is empty
<img width="1656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04ebf71dc44fc6c24946614dcc1c278001d0beae/Screenshot%202023-12-12%20at%2010.22.02%E2%80%AFAM.png" alt="Screenshot 2023-12-12 at 10.22.02 AM.png" />

4. Refresh the page and the pumping test should now be deleted from this well.
-- You should also see that the pumpting test in `aquifer_parameters` table no longer has a `well_tag_number`
<img width="1646" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDVUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ab9b3ecb9416cf8b624d5ae1ca7e2848f51b63e/Screenshot%202023-12-12%20at%2010.26.22%E2%80%AFAM.png" alt="Screenshot 2023-12-12 at 10.26.22 AM.png" />
