### ISSUE TITLE
Not all classes of well render in select menu

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/gwells#2130]
**Describe the Bug**
When creating or editing a new well and selected `Class of well`, two options are missing from the select menu `Dewatering` and `Drainage` (These are separate from `Dewatering/drainage`)

**Expected Behaviour**
When the menu appears the values for `Dewatering` and `Drainage` are selectable

**Actual Behaviour**
The two fields are missing

![Image](https://github.com/bcgov/gwells/assets/62873746/eefdb79c-d993-4172-8d3c-3ffa4e3eef9c)

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Edit or create a well
2. Select 'Class of Well'

## Additional Notes:
- If you look in the `well_class_code` table, the two missing fields are there which should cause them to populate in the select menu.
- The entries in the table have an expiry date predating today that is causing the bug
- Work will likely just need a `Command` to be written and the file containing the codes be updated

**Comment by LocalNewsTV** [comment]
Initial investigation suggests the codes were stored in `fixture` file like we are used to seeing. This was deliberately removed 3 years ago, and they replaced them with a single migration. due to a conflict they were having at that time.

https://github.com/bcgov/gwells/pull/1744/files#diff-82799ae709757a132ea2566e9f07c8ddf4d07a021f8a87eccba878d9df743d9e

**Comment by fergmac** [comment]
@LocalNewsTV were you able to find any context on what the conflict they were having was?

Based on a chat and call I had with Su, I'm going to close this bug ticket:

I just want to confirm that we do want to reintroduce the separate 'Dewatering' and 'Drainage' well classes?
These fields were expired a few years ago due to an issue.
 
When I query the production database I get the following:
 
select count(*) from well where well.well_class_code = 'DEWATERING';  = 0
select count(*) from well where well.well_class_code = 'DRAINAGE';       = 0
select count(*) from well where well.well_class_code = 'DEW_DRA';        = 439
 
 
If we are reintroducing 'Dewatering' and 'Drainage', should we:
- Deprecate the 'Dewatering/Drainage' class?
- Leave all historical instances of wells with a class code of 'DEW_DRA' as is? I don't see that there is any other indicators we could use to reassign wells from class code 'DEW_DRA' to either 'DEWATERING' or 'DRAINAGE'.
- Only assign new well submissions with class code 'DEWATERING' or 'DRAINAGE' when applicable?

Response:
As we just discussed in the call, please remove the data validation requirements for dewatering/permanent wells (data validation ticket 2112)  and close this bug ticket for now as 1. I don't want to reopen the issue, 2. splitting is harder than combing, 3. compare with the works and risks, I don't see much value to split them considering the number of dewatering/drainage wells. Thank you!

**Comment by LocalNewsTV** [comment]
@fergmac The short answer: No.

This bug ticket was made towards end of day after a conversation with the Service owner about ticket #2112 
I found the PR where it was changed through Git blame and added it for the additional context. But since #2112 was taken off my hands, I never pursued it further.
