### ISSUE TITLE
Incorporating WALLY Cross Section into GWELLS

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#2236]
**Problem Description** 
The Ground water staff are interested in incorporating the WALLY cross section tool into GWELLs the rationale is that this is the only relevant ground water tool in WALLY so it makes moresense for it to exist in GWELLS, additionally GWELLS has more refined data for the cross section tool.

currently the tool is a part of wally this ticket is to determine how difficult it would be to decouple the Xsection Tool from Wally, ensure that GWELLS has access to the relevant GEOspatial data for the tool to be useful and finally add the tool to GWELLS

Cross section tool link:
https://wally.nrs.gov.bc.ca/section?section_line_A=-124.0842703544857&section_line_A=48.84525550583385&section_line_B=-124.0945991576184&section_line_B=48.80468947940966

**Timebox**
- How much effort are we committing to this research?
- up to 1 sprint worth of time can be committed to this work 

**Outcome**
Details describing the outcome of the research 
- a plan for how this work could be completed broken down into unrefined tickets
- an estimation of how long this work might take for funding purposes
- a list of which geospatial layers need to be added to GWELLS in order for the too to be usable

![Image](https://github.com/bcgov/gwells/assets/103149911/fbbe9940-5b9d-4424-a718-7718a22f35b0)

![Image](https://github.com/bcgov/gwells/assets/103149911/47fbf1b4-ade0-450f-8c65-c85f46437804)

**Comment by acatchpole** [comment]
# Results of Research:

It is fully practicable to move the Cross Section Analysis from WALLY into GWELLS. This tool is used by hydrogeologists when doing well permitting applications to be able to visualize the local water table and what is already accessing that water. Because of the uncertainty around WALLY (whether it will continue to be available), the aquifer dashboard team is interested in moving the Cross Section Analysis tool into the more maintained GWELLS.

GWELLS shares many qualities that WALLY relies on to serve this tool:
    - Vue frontend
    - PostgresDB / dirty,PostGIS
    - Python backend (Django vs FastAPI)
    - Get and serve a variety of geospatial data
    - Mapbox

### Required Data
To use the tool, two points are selected on a map. Those coordinates, along with a customizable search radius, are passed to the '/sections' endpoint. 
- This query returns:
    * all wells in the search area (with location, elevation, and lithology) 
      - *Data source*: ```GWELLS ```
         *\*note\**: the lithology is collected by a separate query to GWELLS as it is a separate endpoint, and then the data is aggregated.
    * all waterbodies (with location and elevation) 
        - *Data source*: ```https://openmaps.gov.bc.ca/geo/pub/wfs?```
    * the surface elevation profile (the elevation at regular points along the line) 
        - *Data source*:```http://geogratis.gc.ca/services/elevation/cdem/profile.json?path={line}&steps={steps}```
        - 
 A copy of some actual query and response objects can be found in the SUSTEAM WALLY Teams channel sharepoint.

Looking at these data sources, we can see that ***no data needs to be added to GWELLS for this feature to function***. That said, there are several water and elevation related map layers that WALLY currently supports and that is stored in the database. These are the Canadian Digital Elevation Maps (CDEM) and Freshwater Atlas collections. BUT, these layers are not needed (and probably not commonly used) for this tool to function.

### Tasks to be done
1. Translate and move WALLY FastAPI to GWELLS Django
   - API code to move = ```backend/api/v1/elevations```, ```backend/api/v1/wells```, ```backend/api/v1/streams```
        **NOTE:** not all funtionality present in these files is needed for the x-section tool.
   - ```backend/api/v1/aggregator/controller.py:databc_feature_search``` is also used.
   - the endpoint that the front end queries is ```/section[/export]``` in the 'wells' routes 
2. Create a new page/tab for the tool.
   - as this tool is fairly computationally expensive, it should likely not be available to general users. We could effectively confine it to desired users by checking for the ```wally_view``` or ```wells_edit``` keycloak roles. (need to confirm...)
3. Add the mapbox to the page. As the WALLY mapbox has a lot of other WALLY features associated with it, it would likely be easier to copy the well mapbox from GWELLS and take only what is needed from the WALLY implementation.
4. Add the tool and functionality to the page.
   - As these are already encompassed in vue components, this task should be mostly copy and paste.

As most of the GWELLS adjustments will need to be made in the backend, it might be easier to implement the front end page first.

### Further notes
 - Plotly is the major package that will need to be introduced to GWELLS. As GWELLS and WALLY are on the same vue version, this should be simple to add.
 - The WALLY X-Section tool supports both a 2D and 3D view. The 3D view is a much more complicated tool AND does not seem to provide any substantial increase in functionality. An interview with a single tool-user shows that they never needed or used the 3D option. 3D should only be implemented if specifically requested.
