### ISSUE TITLE
Bulk upload failed with an error message

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2244]
One of our hydrogeologist was trying to do a bulk upload and got an error message. Would anyone be available to help her with this? Thanks!  Please refer to the GWELLS Teams channel for details. 

**Error message:** 
-------------------------
The CSV data conflicts with existing vertical aquifer extents in the GWELLS database. 
You can resolve the conflicts by either:
1. Editing the CSV and re-uploading it
2. Click the well tag numbers below to editing the existing data.
--------------------------

![Image](https://github.com/bcgov/gwells/assets/170471683/02e8e3b3-a8ae-40ef-a7fb-7ef92e6f10a9)

**Comment by acatchpole** [comment]
This is functioning as intended. When doing a Vertical Aquifer Extents Bulk Upload, an error is generated if a well being updated already has vertical aquifer extent data. If the new data is intended to override, the old data must be manually deleted. To do this, click on the well tag number of the wells with the error. That takes you to the manual 'Edit Vertical Aquifer Extents' page. Then:
   1. Remove the existing data
   2. Hit save
![Image](https://github.com/bcgov/gwells/assets/113044739/05f96728-6c4e-45f5-9a72-38baa45c36f5)

Once the existing data is removed, the bulk update will go through.

There is a second type of error found for this particular bulk update indicating that a WTN is present in more than one place. The .csv will need to be edited so that there is only one entry per WTN.

Per user feedback, a change could be made to allow overwriting existing data. Passed to SO to create and prioritize a ticket for that work.
